=== othree/blog/blooog.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://blog.othree.net" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" targetNamespace="http://blog.othree.net" elementFormDefault="qualified" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">
	<xs:element name="blog">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="blogTitle" type="xs:string"/>
				<xs:element name="blogDescription" type="xs:string"/>
				<xs:choice>
					<xs:element name="blogData" type="blogDataType"/>
					<xs:element name="entries" type="entriesType"/>
				</xs:choice>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="listType">
		<xs:annotation>
			<xs:documentation>
			about:about;
			a:all;
			ac:all calendar;
			y:year;
			m:month;
			w:week;
			d:day;
			c:category;
			ca:category all;
			s:single;
			i:index;
			r:recent;
			o:blogroll;
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="anout|a|ac|y|m|w|d|c|ca|s|i|r|o"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:complexType name="articleType">
		<xs:sequence>
			<xs:element name="author" type="authorType"/>
			<xs:element name="datetime" type="datetimeType"/>
			<xs:element name="category" type="xs:string" minOccurs="0"/>
			<xs:element name="title" type="xs:string"/>
			<xs:element name="content" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="summary" type="mainContentType" minOccurs="0"/>
						<xs:element name="mainContent" type="mainContentType"/>
						<xs:element name="extendContent" type="mainContentType" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="entryID" type="xs:integer" use="required"/>
		<xs:attribute name="commentID" type="xs:integer" use="optional"/>
	</xs:complexType>
	<xs:complexType name="authorType">
		<xs:sequence>
			<xs:element name="authorName" type="xs:string"/>
			<xs:element name="authorEmail" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:element>
			<xs:element name="authorUrl" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="blogDataType">
		<xs:sequence>
			<xs:element name="categories">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="category" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="categoryTitle" type="xs:string"/>
									<xs:element name="categoryDescription" type="xs:string"/>
								</xs:sequence>
								<xs:attribute name="categoryID" type="xs:integer" use="required"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="archives">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="archive" minOccurs="0" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="archiveMeta" type="metaType"/>
									<xs:element name="archiveItem" minOccurs="0" maxOccurs="unbounded">
										<xs:complexType>
											<xs:simpleContent>
												<xs:extension base="xs:string">
													<xs:attribute name="archiveCount" type="xs:integer" use="required"/>
												</xs:extension>
											</xs:simpleContent>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="recent">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="recentEntries" type="entriesType" block="restriction" minOccurs="0"/>
						<xs:element name="recentComments" type="commentsType" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="blogID" type="xs:integer" use="required"/>
	</xs:complexType>
	<xs:complexType name="commentsType">
		<xs:sequence>
			<xs:element name="comment" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="commentType">
							<xs:sequence minOccurs="0">
								<xs:element name="entry" type="entryType"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="commentCount" type="xs:integer" use="optional" default="0"/>
	</xs:complexType>
	<xs:complexType name="commentType">
		<xs:complexContent>
			<xs:extension base="articleType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="datetimeType">
		<xs:sequence>
			<xs:element name="date" type="xs:date"/>
			<xs:element name="time" type="xs:time"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="entriesType">
		<xs:sequence>
			<xs:element name="entriesMeta" type="metaType"/>
			<xs:element name="entry" minOccurs="0" maxOccurs="unbounded">
				<xs:complexType>
					<xs:complexContent>
						<xs:extension base="entryType">
							<xs:sequence>
								<xs:element name="comments" type="commentsType"/>
								<xs:element name="trackbacks" type="trackbacksType"/>
							</xs:sequence>
						</xs:extension>
					</xs:complexContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" use="optional">
			<xs:simpleType>
				<xs:restriction base="xs:string"/>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="entryType">
		<xs:complexContent>
			<xs:extension base="articleType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="metaType">
		<xs:sequence>
			<xs:element ref="listType"/>
			<xs:element name="listData" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:string">
							<xs:attribute name="listID" type="xs:string" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="previous" type="mType" minOccurs="0"/>
			<xs:element name="next" type="mType" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mType">
		<xs:sequence>
			<xs:element name="mTitle" type="xs:string" minOccurs="0"/>
			<xs:element name="mData" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="mainContentType" mixed="true">
		<xs:sequence>
			<xs:any namespace="http://www.w3.org/1999/xhtml" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="trackbacksType">
		<xs:sequence>
			<xs:element name="trackback" type="trackbackType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="trackbackCount" type="xs:integer" default="0"/>
		<xs:attribute name="trackbackURL" type="xs:string"/>
	</xs:complexType>
	<xs:complexType name="trackbackType">
		<xs:sequence>
			<xs:element name="pingTitle" type="xs:string"/>
			<xs:element name="datetime" type="datetimeType"/>
			<xs:element name="pingBlogName" type="xs:string"/>
			<xs:element name="pingURL" type="xs:string"/>
			<xs:element name="pingExcerpt" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="entryID" type="xs:integer" use="required"/>
		<xs:attribute name="trackbackID" type="xs:integer" use="required"/>
	</xs:complexType>
</xs:schema>

=== othree/blog/log/2009/05/12/my-blog-is-back.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/main.xsl"?>
<b:blog xmlns="http://www.w3.org/1999/xhtml" xmlns:b="http://blog.othree.net"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blog.othree.net http://blog.othree.net/blooog.xsd">
	<b:blogTitle>O3noBLOG</b:blogTitle>
	<b:blogDescription></b:blogDescription>
	<b:entries>
		<b:entriesMeta>
			<b:listType>s</b:listType>
			<b:listData listID="000583" baseName="my-blog-is-back">My blog is back</b:listData>

			<b:previous>
				<b:mTitle>Opera in Taiwan</b:mTitle>
				<b:mDate>2009-04-30</b:mDate>
				<b:mBase>opera_in_taiwan</b:mBase>
			</b:previous>


			<b:next>
				<b:mTitle>勉勵的話語</b:mTitle>
				<b:mDate>2009-06-02</b:mDate>
				<b:mBase>face-death</b:mBase>
			</b:next>

		</b:entriesMeta>
		<b:entry entryID="000583" baseName="my-blog-is-back">
			<b:author>
				<b:authorName>othree</b:authorName>
				<b:authorEmail>othree@gmail.com</b:authorEmail>
				<b:authorUrl></b:authorUrl>
			</b:author>
			<b:datetime>
				<b:date>2009-05-12</b:date>
				<b:time>11:14:31</b:time>
			</b:datetime>
			<b:category>about</b:category>

			<b:CommentsAccepted>0</b:CommentsAccepted>


			<b:PingsAccepted>0</b:PingsAccepted>

			<b:title>My blog is back</b:title>
			<b:content>
				<b:summary>掛了將近一個月有餘，昨天終於先弄回來，中間一度少掉的文章在 Google Reader 裡都還看的到，所以復原文章也沒花上什麼心力，不過苦工少不了就是，另外在 暫時站 寫的文章也搬過來了，這幾篇同時有用 WTFPL 授權，還順便把 MT 升級到最新的4.25版，本來很想順便改版的，不過一直沒好好設計，這部份就先繼續放著了，反正目前版面我其實還蠻滿意的（除了XHTML實在有夠麻煩）。...</b:summary>
				<b:mainContent><p>掛了將近一個月有餘，昨天終於先弄回來，中間一度少掉的文章在 Google Reader 裡都還看的到，所以復原文章也沒花上什麼心力，不過苦工少不了就是，另外在 <a href="http://othree.github.com">暫時站</a> 寫的文章也搬過來了，這幾篇同時有用 <span class="caps">WTFPL </span>授權，還順便把 MT 升級到最新的4.25版，本來很想順便改版的，不過一直沒好好設計，這部份就先繼續放著了，反正目前版面我其實還蠻滿意的（除了XHTML實在有夠麻煩）。</p></b:mainContent>
				<b:extendContent></b:extendContent>
			</b:content>
			<b:comments commentCount="2">

				<b:comment commentID="098623" entryID="000583">
					<b:author>
						<b:authorName>Thomas</b:authorName>
						<b:authorEmail>web.azltx@gmail.com</b:authorEmail>
						<b:authorUrl></b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2009-05-20</b:date>
						<b:time>18:17:12</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>覺得你的網站使用的中文字體相當好看，想請問這是哪種字體呢？謝謝您！</p>
</b:mainContent>
					</b:content>
				</b:comment>

				<b:comment commentID="098627" entryID="000583">
					<b:author>
						<b:authorName>othree.net</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl>http://blog.othree.net</b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2009-05-21</b:date>
						<b:time>14:43:23</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>我也不確定你看到的是哪種字體耶，我推測有可能是微軟正黑體啦，建議你可以裝Firebug來看看CSS內容比較正確:P</p>
</b:mainContent>
					</b:content>
				</b:comment>

			</b:comments>
			<b:trackbacks trackbackCount="0" trackbackURL="https://othree.net/mt/mt-tb.cgi/581">

			</b:trackbacks>
		</b:entry>
	</b:entries>
</b:blog>

=== othree/blog/log/2005/12/01/lovely-penguin.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="/main.xsl"?>
<b:blog xmlns="http://www.w3.org/1999/xhtml" xmlns:b="http://blog.othree.net"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://blog.othree.net http://blog.othree.net/blooog.xsd">
	<b:blogTitle>O3noBLOG</b:blogTitle>
	<b:blogDescription></b:blogDescription>
	<b:entries>
		<b:entriesMeta>
			<b:listType>s</b:listType>
			<b:listData listID="000288" baseName="lovely-penguin">可愛企鵝圖示</b:listData>

			<b:previous>
				<b:mTitle>與壞電腦為伍的一天</b:mTitle>
				<b:mDate>2005-11-30</b:mDate>
				<b:mBase>a-day-with-broken-computers</b:mBase>
			</b:previous>


			<b:next>
				<b:mTitle>新酷音輸入法支援unicode了</b:mTitle>
				<b:mDate>2005-12-02</b:mDate>
				<b:mBase>chewing-support-unicode</b:mBase>
			</b:next>

		</b:entriesMeta>
		<b:entry entryID="000288" baseName="lovely-penguin">
			<b:author>
				<b:authorName>othree</b:authorName>
				<b:authorEmail>othree@gmail.com</b:authorEmail>
				<b:authorUrl></b:authorUrl>
			</b:author>
			<b:datetime>
				<b:date>2005-12-01</b:date>
				<b:time>23:10:10</b:time>
			</b:datetime>
			<b:category>web</b:category>

			<b:CommentsAccepted>0</b:CommentsAccepted>


			<b:PingsAccepted>0</b:PingsAccepted>

			<b:title>可愛企鵝圖示</b:title>
			<b:content>
				<b:summary> 之前在MSN上看到朋友用了這個企鵝的圖作表情符號，真的很可愛，不過一直找不齊，也找不到來源，前兩天終於有朋友告訴我是哪裡來的了（感動T_T），Emperor Penguin Empire，這些圖片其實是網頁素材，使用規約大致如下： 原作者保留著作權 個人網頁使用OK 不允許任何二次加工 商業網站和網頁製作公司請勿使用 請勿冒名說是自創圖示 大家使用圖片的同時小心不要觸犯了喔。...</b:summary>
				<b:mainContent><p><img src="http://blog.othree.net/log/2005/12/01/lovely_penguin/roll_pen11.gif" alt="轉動的企鵝" /></p>

<p>之前在MSN上看到朋友用了這個企鵝的圖作表情符號，真的很可愛，不過一直找不齊，也找不到來源，前兩天終於有朋友告訴我是哪裡來的了（感動T_T），<a href="http://www.peso.nu/">Emperor Penguin Empire</a>，這些圖片其實是網頁素材，使用規約大致如下：</p>


<ol>
<li>原作者保留著作權</li>
<li>個人網頁使用OK</li>
<li>不允許任何二次加工</li>
<li>商業網站和網頁製作公司請勿使用</li>
<li>請勿冒名說是自創圖示</li>
</ol>



<p>大家使用圖片的同時小心不要觸犯了喔。</p></b:mainContent>
				<b:extendContent></b:extendContent>
			</b:content>
			<b:comments commentCount="7">

				<b:comment commentID="000918" entryID="000288">
					<b:author>
						<b:authorName>Kej</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl>http://kej.tw/</b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2005-12-02</b:date>
						<b:time>00:00:24</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>喔喔喔～我想找他的原始網站也找了好久
沒想到終於在這裡看到了(泣)</p>
</b:mainContent>
					</b:content>
				</b:comment>

				<b:comment commentID="000921" entryID="000288">
					<b:author>
						<b:authorName>瑞明</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl></b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2005-12-06</b:date>
						<b:time>18:22:04</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>這隻不夠可愛！@_@</p>
</b:mainContent>
					</b:content>
				</b:comment>

				<b:comment commentID="000923" entryID="000288">
					<b:author>
						<b:authorName>OOO</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl>http://blog.othree.net</b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2005-12-07</b:date>
						<b:time>10:40:33</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>明明就很可愛>&lt;</p>
</b:mainContent>
					</b:content>
				</b:comment>

				<b:comment commentID="001273" entryID="000288">
					<b:author>
						<b:authorName>213</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl></b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2006-06-15</b:date>
						<b:time>09:48:11</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>(^.^)&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;&#8212;-</p>
</b:mainContent>
					</b:content>
				</b:comment>

				<b:comment commentID="013706" entryID="000288">
					<b:author>
						<b:authorName>ammng</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl>http://http:/</b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2007-03-26</b:date>
						<b:time>17:17:16</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>可愛的企鵝</p>
</b:mainContent>
					</b:content>
				</b:comment>

				<b:comment commentID="013707" entryID="000288">
					<b:author>
						<b:authorName>ammng</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl></b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2007-03-26</b:date>
						<b:time>17:17:38</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>可愛的企鵝</p>
</b:mainContent>
					</b:content>
				</b:comment>

				<b:comment commentID="073371" entryID="000288">
					<b:author>
						<b:authorName>Amma</b:authorName>
						<b:authorEmail></b:authorEmail>
						<b:authorUrl></b:authorUrl>
					</b:author>
					<b:datetime>
						<b:date>2008-07-30</b:date>
						<b:time>17:50:01</b:time>
					</b:datetime>
					<b:content>
						<b:mainContent><p>卡挖依&#8230;好可愛的企鵝喔~>&lt;~   ^^
有誰能跟我說還有哪些可愛的圖示  感恩喔!!</p>
</b:mainContent>
					</b:content>
				</b:comment>

			</b:comments>
			<b:trackbacks trackbackCount="2" trackbackURL="https://othree.net/mt/mt-tb.cgi/287">

				<b:trackback trackbackID="13" entryID="000288">
					<b:pingTitle>帝企鹅帝国: GIF 图标</b:pingTitle>
					<b:datetime>
						<b:date>2005-12-02</b:date>
						<b:time>10:43:09</b:time>
					</b:datetime>
					<b:pingBlogName>3rdeye</b:pingBlogName>
					<b:pingURL>http://3eye.name/blog/?id=111</b:pingURL>
					<b:pingExcerpt><a href="http://www.peso.nu/" rel="nofollow"></a>
<p>QQ 上很多人用这只可爱的企鹅做表情图标~ 一直希望集齐的但苦苦搜寻无果, 今</p></b:pingExcerpt>
				</b:trackback>

				<b:trackback trackbackID="14" entryID="000288">
					<b:pingTitle>可愛的企鵝圖示：Emperor Penguin Empire</b:pingTitle>
					<b:datetime>
						<b:date>2005-12-06</b:date>
						<b:time>23:09:53</b:time>
					</b:datetime>
					<b:pingBlogName>KeBlog‧Kej's weblog</b:pingBlogName>
					<b:pingURL>http://blog.kej.tw/2005-12/06/emperor-penguin-empire/</b:pingURL>
					<b:pingExcerpt>	自從A君丟給我幾個超可愛的企鵝圖示之後，我們倆便開始瘋狂的(?)在網路上尋找哪邊有更多的同系列圖示，並且想找出他的來源或官方網站，但是一直都找不到(太笨？)
	直到前幾天在O3noBLOG ...</b:pingExcerpt>
				</b:trackback>

			</b:trackbacks>
		</b:entry>
	</b:entries>
</b:blog>
